apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nhs-number-api
  namespace: nhsrpysoc
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: nhs-rpysoc.rsna.newtonstree.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nhs-number-api
                port:
                  name: http
  tls:
    - hosts:
        - nhs-rpysoc.rsna.newtonstree.ai