apiVersion: v1
kind: Service
metadata:
  name: nhs-number-api
  namespace: nhsrpysoc
  labels:
    app: nhs-number-api
spec:
  type: ClusterIP
  selector:
    app: nhs-number-api
  ports:
    - name: http
      port: 80
      targetPort: 8888
      protocol: TCP
